[package]
name = "dioxus_docs_site"
version = "0.0.0"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus", features = [
    "web",
    "router",
    "ssr",
] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
log = "0.4.14"
wasm-logger = "0.2.0"
wasm-bindgen = { version = "0.2.78", features = ["enable-interning"] }
once_cell = "1.8.0"
fermi = { git = "https://github.com/dioxuslabs/fermi" }
console_error_panic_hook = "0.1.7"
gloo-history = "0.1.0"


[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
